<?php
/**
 * @copyright Copyright (c) 2014 Sergey Cherepanov (sergey@cherepanov.org.ua)
 * @license Creative Commons Attribution 3.0 License
 */

/** @var Open_Gallery_Block_Item_View $this */
?>
<script src="http://jwpsrv.com/library/Sp6Xhh53EeSiiSIACtqXBA.js"></script>
<h1><?php echo $this->getItem()->getTitle();?></h1>
<?php echo Mage::helper('open_gallery/item_video')->getVideoHtml($this->getItem());?>
