<?php
/**
 * @copyright Copyright (c) 2014 Sergey Cherepanov (sergey@cherepanov.org.ua)
 * @license Creative Commons Attribution 3.0 License
 */

/** @var Open_Gallery_Block_Home $this */
$categoryCollection = $this->getCategoryCollection();
$helper             = Mage::helper('open_gallery');
$imageWidth         = $helper->getCategoryListImageWidth();
$imageHeight        = $helper->getCategoryListImageHeight();
?>
<h1><?php echo $this->__('Open Gallery')?></h1>
<h3><?php echo $this->__('Available Categories')?></h3>
<ul>
    <?php foreach ($categoryCollection as $category):
    /** @var Open_Gallery_Model_Category $category */ ?>
    <li>
        <a href="<?php echo $this->getCategoryUrl($category)?>">
            <img width="<?php echo $imageWidth;?>" height="<?php echo $imageHeight;?>" src="<?php echo $this->getThumbnailUrl($category)?>" alt="<?php echo $category->getTitle();?>" />
        </a>
        <a href="<?php echo $this->getCategoryUrl($category)?>">
            <span><?php echo $category->getTitle();?></span>
        </a>
    </li>
    <?php endforeach;?>
</ul>
